char nativeCharIn();
char nativeCharOut();
char conStat();
char getButtons();
char setOnBoardLEDs();
char charLCDOut();
char controlLCD();
char nativeExit();
char currentTimeMillis();
char ser1In();
char ser1Out();
char ser1Stat();
char ser1RTS();
char ser1DTR();
char pwmStart();
char pwmStop();
char adcGetValue();
#ifdef WITHMON
void Monitor(int);
int GetMilliSec();
int AdcGetValue();
#endif
