boot:
	javac  -verbose -source 1.4 -classpath ./BAJOSBOOT/classes -g:none ./BAJOSBOOT/sources/java/lang/*.java -extdirs . -bootclasspath .
	mv ./BAJOSBOOT/sources/java/lang/*.class  ./BAJOSBOOT/classes/java/lang
	javac  -verbose -source 1.4 -classpath ./BAJOSBOOT/classes -g:none ./BAJOSBOOT/sources/java/io/*.java -extdirs .  -bootclasspath .
	mv ./BAJOSBOOT/sources/java/io/*.class  ./BAJOSBOOT/classes/java/io

graphic:
	javac  -verbose -source 1.4 -classpath ./BAJOSBOOT/classes -g:none ./BAJOSBOOT/sources/java/graphics/*.java -extdirs . -bootclasspath . 
	mv ./BAJOSBOOT/sources/java/graphics/*.class  ./BAJOSBOOT/classes/java/graphics/




avr8:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/avr8/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/avr8/PlatForm.class  ./BAJOSBOOT/classes/platform

evk1100:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/evk1100/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/evk1100/PlatForm.class  ./BAJOSBOOT/classes/platform

linux:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/linux/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/linux/PlatForm.class  ./BAJOSBOOT/classes/platform

avr32-linux:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/avr32-linux/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/avr32-linux/PlatForm.class  ./BAJOSBOOT/classes/platform

ngw100:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/ngw100/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/ngw100/PlatForm.class  ./BAJOSBOOT/classes/platform

stk1000:
	javac  -verbose -g:none -source 1.4 ./BAJOSBOOT/sources/platform/stk1000/PlatForm.java -extdirs . -classpath ./BAJOSBOOT/classes -bootclasspath .
	mv  ./BAJOSBOOT/sources/platform/stk1000/PlatForm.class  ./BAJOSBOOT/classes/platform





